
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

  discovery:

# Text to speech
tts:
  - platform: google_translate
  - platform: reversotts
    language: 'Tyler-Australian-English'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

climate:
  - platform: intesishome
    username: !secret aircon_username
    password: !secret aircon_password

device_tracker:
  - platform: tile
    username: !secret tile_james_username
    password: !secret tile_james_password
    show_inactive: true

binary_sensor:
  - platform: mqtt
    name: "Badgers Driveway Motion"
    device_class: motion
    state_topic: "blueiris/ai/bdriveway"
    payload_on: "bdriveway"
    off_delay: 30

  - platform: mqtt
    name: "Mecon Driveway Motion"
    device_class: motion
    state_topic: "blueiris/ai/mecondriveway"
    payload_on: "mecondriveway"
    off_delay: 30

camera:
  - platform: mjpeg
    mjpeg_url: !secret camera_url_mecondriveway
    name: mecondriveway

  - platform: mjpeg
    mjpeg_url: !secret camera_url_bdriveway
    name: bdriveway

  - platform: mjpeg
    mjpeg_url: !secret camera_url_birdbox
    name: birdbox

api:
  alexa:
    smart_home:

input_select:
  life360_james:
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
  life360_i_shan:
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away

breaking_changes: